schema: 'https://rickandmortyapi.com/graphql'
documents:
    - 'src/**/*.gql'

extensions:
    codegen:
        ignoreNoDocuments: true
        generates:
            src/__generated__/:
                preset: 'client'
            src/__generated__/types.ts:
                plugins:
                    - 'typescript'
                    - 'typescript-operations'
