query GetCharacters($page: Int!) {
    characters(page: $page) {
        info {
            ...PaginationInfo
        }
        results {
            ...TableCharacter
        }
    }
}

fragment PaginationInfo on Info {
    count
    pages
    next
    prev
}

fragment TableCharacter on Character {
    id
    name
    image
}
